name: chat_server

services:
  user_auth:
    build: ..
    environment:
        DB_HOST: $DB_HOST
        DB_USER: $DB_USER
        DB_PASS: $DB_PASS
        DB_DB: $DB_DB
        DB_PORT: $DB_PORT
    hostname: user_auth
    ports:
      - "9999:9999"
    links:
      - "postgres"
    depends_on:
      - postgres
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 2

  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DB
    volumes:
      - ../db/postgres_data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: 4
